### ISSUE TITLE
Broadcast from P5JS?

### ISSUE THREAD

**Issue by owenmcateer** [genekogan/p5js-osc#13]
Hello,
Is it possible to send OSC data from a P5js webpage to be received by Processing or another P5js app?
Thanks

**Comment by genekogan** [comment]
I think the way to do this would be sending data from p5 to the server over websocket, and then sending OSC from the server to Processing.

**Comment by owenmcateer** [comment]
I tried using the following function in the examples but it doesn't appear to work. I think I need to study up on OSC a bit more.

```
function sendOsc(address, value) {
	socket.emit('message', [address].concat(value));
}
```
